"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var serveClosestStops_1 = require("./router/serveClosestStops");
var showIndex_1 = require("./router/showIndex");
var serveLine_1 = require("./router/serveLine");
var showLinemap_1 = require("./router/showLinemap");
var express = require('express');
var app = express();
var parser = require("body-parser");
app.use(parser.json());
app.use(parser.urlencoded({ extended: true }));
app.get('/closestStops', serveClosestStops_1.serveClosestStops);
app.get('/', showIndex_1.showIndex);
app.get('/line', serveLine_1.serveLine);
app.get("/linemap", showLinemap_1.showLinemap);
app.use(express.static('./workspace/view'));
app.use(express.static('./workspace/public'));
app.listen(3000, function () { return console.log('Our fantastic app listening on port 3000!'); });
module.exports = app;
//# sourceMappingURL=server.js.map